(function(g){var window=this;'use strict';var Om=function(r){r.publish("cardstatechange",r.Fy()&&r.Re()?1:0)},p_=function(r,D){var Y=g.oo(D),V=Y?D:arguments;
for(Y=Y?0:1;Y<V.length;Y++){if(r==null)return;r=r[V[Y]]}return r},X0r=function(r){var D=g.Of(r);
r=g.lc(r);return new g.yK(D.x,D.y,r.width,r.height)},o7M=function(r,D,Y){var V=V===void 0?{}:V;
var L;return L=g.KK(r,D,function(){g.lK(L);Y.apply(r,arguments)},V)},ip=function(r){r=g.HW(r);
delete hj[r];g.lu(hj)&&tj&&tj.stop()},n7S=function(){tj||(tj=new g.LN(function(){Per()},20));
var r=tj;r.isActive()||r.start()},Per=function(){var r=g.D0();
g.gI(hj,function(D){HVq(D,r)});
g.lu(hj)||n7S()},Jj=function(r,D,Y,V){g.u_.call(this);
if(!Array.isArray(r)||!Array.isArray(D))throw Error("Start and end parameters must be arrays");if(r.length!=D.length)throw Error("Start and end points must be the same length");this.T=r;this.N=D;this.duration=Y;this.j=V;this.coords=[];this.progress=this.D=0;this.S=null},HVq=function(r,D){D<r.startTime&&(r.endTime=D+r.endTime-r.startTime,r.startTime=D);
r.progress=(D-r.startTime)/(r.endTime-r.startTime);r.progress>1&&(r.progress=1);r.D=1E3/(D-r.S);r.S=D;fwW(r,r.progress);r.progress==1?(r.W=0,ip(r),r.onFinish(),r.uv()):r.isPlaying()&&r.sO()},fwW=function(r,D){typeof r.j==="function"&&(D=r.j(D));
r.coords=Array(r.T.length);for(var Y=0;Y<r.T.length;Y++)r.coords[Y]=(r.N[Y]-r.T[Y])*D+r.T[Y]},w0a=function(r,D){g.NF.call(this,r);
this.coords=D.coords;this.x=D.coords[0];this.y=D.coords[1];this.z=D.coords[2];this.duration=D.duration;this.progress=D.progress;this.fps=D.D;this.state=D.W},K_=function(r,D,Y,V,L){Jj.call(this,D,Y,V,L);
this.element=r},rRe=function(r,D,Y,V,L){if(D.length!=2||Y.length!=2)throw Error("Start and end points must be 2D");
K_.call(this,r,D,Y,V,L)},DgR=function(r){return Math.pow(r,3)},Y15=function(r){return 3*r*r-2*r*r*r},VsR=function(r){g.N.call(this);
this.T=r||window;this.W=[]},lp=function(r){return r.baseUrl||null},Em=function(r,D){return g.aX(g.l1(r,D),function(Y){return!!Y})},Lvr=function(r,D,Y){function V(xw){var rQ=xw.hovercardButton;
if(!rQ)return null;rQ=rQ.subscribeButtonRenderer;if(!rQ)return null;var c=T(rQ.unsubscribedButtonText),w=T(rQ.subscribedButtonText);if(rQ.subscribed){var u=T(rQ.subscriberCountWithUnsubscribeText);var C=T(rQ.subscriberCountText)}else u=T(rQ.subscriberCountText),C=T(rQ.subscriberCountWithSubscribeText);var bf=null;if(xw.signinEndpoint){bf=p_(xw,"signinEndpoint","webNavigationEndpointData","url");if(!bf){var kc,s_;bf=(s_=g.e((kc=rQ.signInEndpoint)==null?void 0:kc.commandMetadata,g.FZ))==null?void 0:
s_.url}if(!bf)return null}return c&&(w||bf)?{subscribed:rQ.subscribed,subscribeText:c,subscribeCount:u,unsubscribeText:w,unsubscribeCount:C,enabled:rQ.enabled,signinUrl:bf,classic:xw.useClassicSubscribeButton}:null}
function L(xw){if(xw){var rQ=[],c=xw.videoId;c&&rQ.push("v="+c);(c=xw.playlistId)&&rQ.push("list="+c);(xw=xw.startTimeSeconds)&&rQ.push("t="+xw);return"/watch?"+rQ.join("&")}}
function T(xw){if(!xw)return null;var rQ=xw.simpleText;return rQ?rQ:xw.runs?g.l1(xw.runs,function(c){return c.text}).join(""):null}
D=D.endscreenElementRenderer;if(!D)return null;var I=D.style,B=D.endpoint||{},m=null,G=null,M=!1,Q=null,y=null,a=null,W=null,q=!1,A=null,p=null,t=null,l=null,d=null,b=null;if(I==="VIDEO")g.e(B,g.Z5)?m=g.e(B,g.Z5).url:(b=g.e(B,g.L9),m=L(b)),G=!1,Q=r,D.thumbnailOverlays?(M=D.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,y=T(M.text),M=M.style==="LIVE"):y=T(D.videoDuration);else if(I==="PLAYLIST")g.e(B,g.Z5)?m=g.e(B,g.Z5).url:(b=g.e(B,g.L9),m=L(b)),G=!1,Q=r,a=T(D.playlistLength);else if(I===
"CHANNEL"){if(q=p_(B,"browseEndpoint","browseId"))W=q,m="/channel/"+W;G=!1;Q="new";(q=!!D.isSubscribe)?A=V(D):p=T(D.subscribersText)}else I==="WEBSITE"?((t=p_(B,"urlEndpoint","url"))&&(m=t),G=!0,Q="new",t=D.icon.thumbnails[0].url):I==="CREATOR_MERCHANDISE"&&(D.productPrice&&(l=T(D.productPrice)),D.additionalFeesText&&(d=T(D.additionalFeesText)),(G=p_(B,"urlEndpoint","url"))&&(m=G),G=!0,Q="new");r=p_(D,"title","accessibility","accessibilityData","label");var n=D.endpoint?D.endpoint.clickTrackingParams:
null,P="";if(D.metadata){var Ly=T(D.metadata);Ly&&(P=Ly)}return{id:"element-"+Y,type:I,title:T(D.title),metadata:P,callToAction:T(D.callToAction),vU:D.image,iconUrl:t,left:Number(D.left),width:Number(D.width),top:Number(D.top),aspectRatio:Number(D.aspectRatio),startMs:Math.floor(Number(D.startMs)),endMs:Math.floor(Number(D.endMs)),videoDuration:y,j8:M,playlistLength:a,channelId:W,subscribeButton:A,subscribersText:p,isSubscribe:q,targetUrl:m||null,x2I:G,sessionData:n?{itct:n}:null,qaD:Q,Vi:r?r:null,
isPlaceholder:D.isPlaceholder,impressionUrls:Em(D.impressionUrls||[],lp),BTP:Em(D.hovercardShowUrls||[],lp),clickUrls:Em(B.loggingUrls||[],lp),visualElement:g.K0(D.trackingParams),productPrice:l,additionalFeesText:d,watchEndpoint:b||null}},Tge=function(r,D){var Y={startMs:Math.floor(Number(r.startMs)),
impressionUrls:Em(r.impressionUrls||[],lp),elements:Em(r.elements||[],function(V,L){return Lvr(D,V,L)})};
r.trackingParams&&(Y.visualElement=g.K0(r.trackingParams));return Y},IlW=function(r){g.uF.call(this,r);
this.S=this.endscreen=null;this.T={};this.D={};this.j=this.L=null;this.K=[];this.W=null;this.Tv=!0;this.N=0;r=r.Z();this.Y=g.vo(r)||g.eL(r);this.events=new g.Cc(this);g.v(this,this.events);this.events.X(this.player,g.ye("creatorendscreen"),this.onCueRangeEnter);this.events.X(this.player,g.aB("creatorendscreen"),this.onCueRangeExit);this.events.X(this.player,"resize",this.QW);this.events.X(window,"focus",this.s$z);this.load();var D=g.Li("STYLE");(g.PJ("HEAD")[0]||document.body).appendChild(D);this.addOnDisposeCallback(function(){g.mJ(D)});
D.sheet&&(D.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),D.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},xgS=function(r){return r.player.getVideoData().Jj?"current":r.Y?"new":"current"},RH=function(r){return r.player.Z().playerStyle==="creator-endscreen-editor"},BgT=function(r){var D=r.player.getVideoData(),Y=D.videoId;
r.S&&r.S.abort();Y={method:"POST",onFinish:function(L){var T=r.S=null;L.status===200&&(L=L.responseText,L.substring(0,3)===")]}"&&(L=L.substring(3),T=JSON.parse(L),T=Tge(T,xgS(r))));zS(r,T)},
urlParams:{v:Y},withCredentials:!0};r.Y&&(Y.urlParams.ptype="embedded");var V=D.mq;V&&(Y.postParams={ad_tracking:V});if(D=g.Mmo(D))if(D=g.zX(D),D=g.ln(D))r.S=g.EA(D,Y)},zS=function(r,D,Y){Y=Y===void 0?!0:Y;
r.player.Me("creatorendscreen");r.L&&(r.L.dispose(),r.L=null,r.j.dispose(),r.j=null);for(var V=g.F(Object.values(r.T)),L=V.next();!L.done;L=V.next())L.value.dispose();r.T={};r.D={};r.K.length>0&&(r.K.forEach(function(B){B.dispose()}),r.K.length=0);
r.W&&(g.Wf(r.W,"ytp-ce-element-show"),r.W.setAttribute("aria-hidden","true"));r.N=0;if((r.endscreen=D)&&D.elements){Y&&mgM(r);Y=[];V=new g.Qe(D.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});Y.push(V);r.player.Z().T||(r.L=new g.Z({G:"div",U:"ytp-ce-shadow"}),g.NI(r.player,r.L.element,4),r.j=new g.Mb(r.L,200));for(V=0;V<D.elements.length;++V){L=D.elements[V];var T=GX5(r,L);if(T){r.T[L.id]=T;r.D[L.id]=L;g.NI(r.player,T.element,4);var I=new g.Qe(L.startMs,L.endMs,{id:"ytp-ce-element-"+
L.id,namespace:"creatorendscreen"});Y.push(I);MsR(r,T,L)}else g.C0(new g.Vw("buildEndscreenElement null",L))}r.player.a$(Y);r.QW()}},mgM=function(r){var D=g.Ed(),Y=g.Rp();
Y&&D&&r.endscreen.visualElement&&g.xL(g.VE)(void 0,Y,D,r.endscreen.visualElement)},GX5=function(r,D){var Y=null;
switch(D.type){case "VIDEO":r={G:"div",hT:["ytp-ce-element","ytp-ce-video"],J:{tabindex:"0","aria-label":D.Vi||"","aria-hidden":"true"},B:[{G:"div",U:"ytp-ce-element-shadow"},{G:"div",U:"ytp-ce-covering-image",J:dW(D)},{G:"div",U:"ytp-ce-covering-shadow-top"},{G:"a",U:"ytp-ce-covering-overlay",J:{href:Sq(r,D.targetUrl),tabindex:"-1"},B:[{G:"div",hT:["ytp-ce-video-title","ytp-webkit-ellipsis"],J:{dir:g.A2(D.title||"")},SD:D.title},{G:"div",U:D.j8?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
SD:D.videoDuration||void 0}]}]};Y=new g.Z(r);break;case "PLAYLIST":r={G:"div",hT:["ytp-ce-element","ytp-ce-playlist"],J:{tabindex:"0","aria-label":D.Vi||"","aria-hidden":"true"},B:[{G:"div",U:"ytp-ce-element-shadow"},{G:"div",U:"ytp-ce-covering-image",J:dW(D)},{G:"div",U:"ytp-ce-covering-shadow-top"},{G:"a",U:"ytp-ce-covering-overlay",J:{href:Sq(r,D.targetUrl),tabindex:"-1"},B:[{G:"div",hT:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],J:{dir:g.A2(D.title||"")},SD:D.title},{G:"div",U:"ytp-ce-playlist-count",
B:[{G:"div",U:"ytp-ce-playlist-icon"},{G:"div",U:"ytp-ce-playlist-count-text",SD:D.playlistLength||void 0}]}]}]};Y=new g.Z(r);break;case "CHANNEL":Y={G:"div",hT:["ytp-ce-element","ytp-ce-channel",D.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],J:{tabindex:"0","aria-label":D.Vi||"","aria-hidden":"true"},B:[{G:"div",U:"ytp-ce-element-shadow"},{G:"div",U:"ytp-ce-expanding-overlay",B:[{G:"div",U:"ytp-ce-expanding-overlay-hider"},{G:"div",U:"ytp-ce-expanding-overlay-background"},{G:"div",U:"ytp-ce-expanding-overlay-content",
B:[{G:"div",U:"ytp-ce-expanding-overlay-body",B:[{G:"div",U:"ytp-ce-expanding-overlay-body-padding",B:[{G:"a",hT:["ytp-ce-channel-title","ytp-ce-link"],J:{href:Sq(r,D.targetUrl),target:"_blank",tabindex:"-1",dir:g.A2(D.title||"")},SD:D.title},D.subscribeButton?{G:"div",U:"ytp-ce-subscribe-container",B:[{G:"div",U:"ytp-ce-channel-subscribe"}]}:"",D.subscribersText?{G:"div",U:"ytp-ce-channel-subscribers-text",SD:D.subscribersText}:"",D.metadata?{G:"div",hT:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],SD:D.metadata}:""]}]}]}]},{G:"div",U:"ytp-ce-expanding-image",J:dW(D)}]};Y=new g.Z(Y);var V=g.HJ(document,"div","ytp-ce-channel-subscribe",Y.element)[0];if(D.subscribeButton&&D.channelId){g.yO(V,"ytp-ce-subscribe-button");if(r.player.Z().T){var L=null;var T=D.sessionData.itct}else L="endscreen",T=null;L=new g.re(D.subscribeButton.subscribeText,D.subscribeButton.subscribeCount,D.subscribeButton.unsubscribeText,D.subscribeButton.unsubscribeCount,!!D.subscribeButton.enabled,!!D.subscribeButton.classic,
D.channelId,!!D.subscribeButton.subscribed,L,T,r.player,!1);V.appendChild(L.element);r.K.push(L)}break;case "WEBSITE":r={G:"div",hT:["ytp-ce-element","ytp-ce-website"],J:{tabindex:"0","aria-label":D.Vi||"","aria-hidden":"true"},B:[{G:"div",U:"ytp-ce-element-shadow"},{G:"div",U:"ytp-ce-expanding-overlay",B:[{G:"div",U:"ytp-ce-expanding-overlay-hider"},{G:"div",U:"ytp-ce-expanding-overlay-background"},{G:"div",U:"ytp-ce-expanding-overlay-content",B:[{G:"div",U:"ytp-ce-expanding-overlay-body",B:[{G:"div",
U:"ytp-ce-expanding-overlay-body-padding",B:[{G:"div",U:"ytp-ce-website-title",J:{dir:g.A2(D.title||"")},SD:D.title},{G:"div",U:"ytp-ce-website-metadata",SD:D.metadata},{G:"a",hT:["ytp-ce-website-goto","ytp-ce-link"],J:{href:Sq(r,D.targetUrl),target:"_blank",tabindex:"-1"},SD:D.callToAction}]}]}]}]},{G:"div",U:"ytp-ce-expanding-image",J:dW(D)},{G:"div",U:"ytp-ce-expanding-icon",J:jPR(D.iconUrl)}]};Y=new g.Z(r);break;case "CREATOR_MERCHANDISE":Y="",D.productPrice&&(Y={G:"div",U:"ytp-ce-merchandise-price-container",
B:[{G:"div",U:"ytp-ce-merchandise-price",SD:D.productPrice}]},D.additionalFeesText&&Y.B.push({G:"div",U:"ytp-ce-merchandise-additional-fees",SD:D.additionalFeesText})),r={G:"div",hT:["ytp-ce-element","ytp-ce-merchandise"],J:{tabindex:"0","aria-label":D.Vi||"","aria-hidden":"true"},B:[{G:"div",U:"ytp-ce-element-shadow"},{G:"div",U:"ytp-ce-expanding-overlay",B:[{G:"div",U:"ytp-ce-expanding-overlay-hider"},{G:"div",U:"ytp-ce-expanding-overlay-background"},{G:"div",U:"ytp-ce-expanding-overlay-content",
B:[{G:"div",U:"ytp-ce-expanding-overlay-body",B:[{G:"div",U:"ytp-ce-expanding-overlay-body-padding",B:[{G:"div",U:"ytp-ce-merchandise-title",J:{dir:g.A2(D.title||"")},SD:D.title},Y,{G:"div",U:"ytp-ce-merchandise-metadata",SD:D.metadata},{G:"a",hT:["ytp-ce-merchandise-goto","ytp-ce-link"],J:{href:Sq(r,D.targetUrl),target:"_blank",tabindex:"-1"},SD:D.callToAction}]}]}]}]},{G:"div",U:"ytp-ce-expanding-image",J:dW(D)},{G:"div",U:"ytp-ce-merchandise-invideo-cta-container",B:[{G:"div",U:"ytp-ce-merchandise-invideo-cta",
SD:D.callToAction||void 0}]}]},Y=new g.Z(r)}D.isPlaceholder&&g.yO(Y.element,"ytp-ce-placeholder");return Y},dW=function(r){if(r.vU)var D=r.vU.thumbnails;
return jPR(D?D[D.length-1].url:null)},jPR=function(r){return r?{style:"background-image: url("+r+")"}:{}},MsR=function(r,D,Y){function V(m){m&&(D.listen("blur",function(){m.style.display!="none"&&r.Tv&&m.focus()}),D.X(m,"focus",T),D.X(m,"blur",I))}
function L(m){r.N+=m;r.N>0?(g.yO(D.element,"ytp-ce-force-expand"),NA(r,Y.id,!0)):(g.Wf(D.element,"ytp-ce-force-expand"),g.Wf(D.element,"ytp-ce-element-hover"),NA(r,Y.id,!1))}
function T(){L(1)}
function I(){L(-1)}
D.listen("mouseenter",function(){QPS(r,D,Y)});
D.listen("mouseleave",function(){sPc(r,D,Y)});
r.player.Z().T||D.listen("click",function(){g.yO(D.element,"ytp-ce-element-hover")});
D.listen("click",function(m){yR0(r,Y,m)});
D.listen("keypress",function(m){yR0(r,Y,m)});
D.listen("focus",function(){QPS(r,D,Y)});
D.listen("blur",function(){sPc(r,D,Y)});
D.listen("touchstart",function(){QPS(r,D,Y)});
var B=g.fB("ytp-ce-expanding-overlay-hider",D.element);B&&D.X(B,"touchstart",function(m){m.stopPropagation();g.Wf(D.element,"ytp-ce-element-hover");g.Wf(D.element,"ytp-ce-force-expand")});
D.listen("keydown",function(m){r.Tv=m.keyCode===9&&!m.shiftKey});
V(g.fB("ytp-sb-subscribe",D.element));V(g.fB("ytp-sb-unsubscribe",D.element));D.listen("focus",T);D.listen("blur",I)},yR0=function(r,D,Y){if(D.targetUrl&&(!Y||Y.type!=="keypress"||Y.keyCode===13)){for(var V=Y.target;V&&!g.s3(V,"ytp-ce-element");){g.s3(V,"subscribe-label")&&alq(r,D);
if(g.s3(V,"ytp-ce-channel-subscribe"))return;V=V.parentElement||null}if(!V||g.s3(V,"ytp-ce-element-hover")){Y.preventDefault();Y.stopPropagation();if(V=r.T[D.id])sPc(r,V,D),V.element.blur();if(Y.ctrlKey||Y.metaKey||D.qaD==="new")alq(r,D),r.player.sendVideoStatsEngageEvent(17,void 0),r.player.pauseVideo(),Y=g.zX(Sq(r,D.targetUrl)),Y=g.ln(Y),g.w1(Y,void 0,D.sessionData);else{var L=g.YA(r.player.Z())||r.player.getVideoData().Jj,T=function(){var I=Sq(r,D.targetUrl),B=D.sessionData,m=D.watchEndpoint,G=
g.Qk(I);L&&G&&(G.v||G.list)?r.player.Ie(G.v,B,G.list,!1,void 0,m||void 0):g.fd(I,B)};
alq(r,D,function(){r.player.sendVideoStatsEngageEvent(17,T)})}}}},Sq=function(r,D){r=r.player.Z();
if(D){if(D.startsWith("//"))return r.protocol+":"+D;if(D.startsWith("/"))return g.m0(r)+D}else return"";return D},QPS=function(r,D,Y){g.s3(D.element,"ytp-ce-element-hover")||(Y.type==="VIDEO"||Y.type==="PLAYLIST"?g.yO(D.element,"ytp-ce-element-hover"):r.player.Z().T?(new g.LN(function(){g.yO(D.element,"ytp-ce-element-hover")},200)).start():g.yO(D.element,"ytp-ce-element-hover"),vn(r,Y.BTP),NA(r,Y.id,!0))},sPc=function(r,D,Y){g.Wf(D.element,"ytp-ce-element-hover");
g.Wf(D.element,"ytp-ce-force-expand");NA(r,Y.id,!1)},NA=function(r,D,Y){r.L&&(Y?r.j.show():r.j.hide());
for(var V=g.F(Object.keys(r.T)),L=V.next();!L.done;L=V.next())L=L.value,L!==D&&g.Fw(r.T[L].element,"ytp-ce-element-shadow-show",Y)},vn=function(r,D,Y){function V(){T||(L++,L===D.length&&(I.stop(),Y&&Y()))}
if(!D||D.length===0||RH(r))Y&&Y();else{D=WvT(r,D);var L=0,T=!1,I=new g.LN(function(){T=!0;Y&&Y()},1E3,r);
I.start();for(r=0;r<D.length;r++)g.Hh(D[r],V)}},alq=function(r,D,Y){vn(r,D.clickUrls,Y);
(r=g.Rp())&&D.x2I&&g.s6(r,D.visualElement)},WvT=function(r,D){var Y=r.player.getVideoData().clientPlaybackNonce;
r=r.player.getCurrentTime().toFixed(2);Y={CPN:Y,AD_CPN:Y,MT:r};r=[];for(var V=0;V<D.length;V++)r.push(Ugc(D[V],Y));return r},Ugc=function(r,D){return r.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(Y){var V=unescape(Y);
V=V.substring(1,V.length-1);return D[V]?escape(D[V]):Y})},Fvq=function(r){return typeof r==="string"?r:""},bp=function(r,D,Y){for(var V in D)if(D[V]===r)return r;
return Y},uUx=function(r,D,Y,V){this.value=r;
this.target=D;this.showLinkIcon=Y;this.W=V},eq=function(r){return r.value?r.value:null},cn=function(r){if(!r)return null;
var D=g.zX(Fvq(r.value));D=g.ln(D);if(!D)return null;var Y=bp(r.target,q15,"current");if(Y==null)r=null;else{var V=r.show_link_icon;r=new uUx(D,Y,V==="true"||V==="false"?V==="true":!0,r.pause_on_navigation!=null?r.pause_on_navigation:!0)}return r},kXS=function(r,D,Y){this.type=r;
this.trigger=D;this.url=Y},ARr=function(r){if(!r)return null;
var D=bp(r.type,gCe),Y=bp(r.trigger,$gR);r=r.url;r=Array.isArray(r)&&r.length?r[0]:r;r=cn(r?r:null);return D?new kXS(D,Y,r):null},OuT=function(r,D,Y,V,L){this.id=r;
this.type=D;this.style=Y;this.data=L;this.action=V||[]},pr5=function(r,D){return g.PS(r.action,D)},hpS=function(r,D){this.context=r;
this.W=D},tsr=function(r){return r.customMessage?C_("div","iv-card-message",r.customMessage):""},ZQ=function(r,D){r="background-image: url("+r+");";
var Y=[];D&&Y.push(D);return{G:"div",U:"iv-card-image",J:{style:r},B:Y}},iua=function(r){if(!r.metaInfo||r.metaInfo.length===0)return"";
var D=[];r=g.F(r.metaInfo);for(var Y=r.next();!Y.done;Y=r.next())D.push(C_("li","",Y.value));return{G:"ul",U:"iv-card-meta-info",B:D}},C_=function(r,D,Y){D?typeof D==="string"?D={"class":D}:Array.isArray(D)&&(D={"class":D.join(" ")}):D={};
D.dir=g.A2(Y);return{G:r,J:D,SD:Y}},JR0=function(r){if(!r.customMessage)return"";
var D=["iv-card-action","iv-card-primary-link"],Y={};r.KN&&(D.push("iv-card-action-icon"),Y.style="background-image: url("+r.KN+");");Y.dir=g.A2(r.customMessage);var V=[{G:"span",SD:r.customMessage}];r.showLinkIcon&&(V.push("\u00a0"),V.push({G:"span",U:"iv-card-link-icon"}));return{G:"div",hT:D,J:Y,B:V}},Xr=function(r,D,Y,V){if(V){D=g.F(D);
for(var L=D.next();!L.done;L=D.next())r.W(L.value,V,Y.id,Y.sessionData,Y.tf.click,5)}},Kvq=function(r,D){this.merchant=r;
this.price=D},llT=function(r){var D;
(D=r)&&!(D=r.length>1?r.charAt(0)==="/"&&r.charAt(1)!=="/":r==="/")&&(D=r.replace(/^(https?:)?\/\//,"").split("/",1),D=!D||D.length<1||!D[0]?[]:D[0].toLowerCase().split(".").reverse(),D=D[0]==="com"&&D[1]==="youtube"||D[0]==="be"&&D[1]==="youtu");return D?r.indexOf("/redirect?")===-1:!1},ECq=function(r,D){return D?D:llT(r)?"current":"new"},oH=function(r,D){g.N.call(this);
var Y=this;this.element=r;this.context=D;this.JT=!1;this.b$=new Map;this.UI=new Map;this.context.C.addEventListener(g.ye("annotations_module"),function(V){(V=Y.b$.get(V))&&V.apply(Y)});
this.context.C.addEventListener(g.aB("annotations_module"),function(V){(V=Y.UI.get(V))&&V.apply(Y)})},Pn=function(r,D,Y,V,L,T,I){r.context.W.listen(D,"click",function(B){r.Nk(Y,V,L,T||[],I||0,B)});
r.context.W.listen(D,"touchstart",function(){r.JT=!1});
r.context.W.listen(D,"touchmove",function(){r.JT=!0})},Rp5=function(r){var D;
return((D=g.e(r,g.Z5))==null?0:D.url)?g.e(r,g.Z5).url:(r=g.e(r,g.L9))&&r.videoId?(D="/watch?v="+r.videoId,r.playlistId&&(D+="&list="+r.playlistId),r.index&&(D+="&index="+r.index),r.startTimeSeconds&&(D+="&t="+r.startTimeSeconds),D):null},n_=function(r,D,Y){return{Tg:(r.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
click:(Y.loggingUrls||[]).map(function(V){return V.baseUrl||""}),
close:(D.dismissLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
vO:(D.impressionLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""}),
f$:(D.clickLoggingUrlsV2s||[]).map(function(V){return V.baseUrl||""})}},zpe=function(r,D,Y){oH.call(this,D,Y);
var V=this;this.C=r;this.eventId=null;this.z5=this.eD=this.l8=this.L=this.isInitialized=!1;this.cards=[];this.Bo=this.K=this.rT=this.j=this.u$=this.W=null;this.Tv=[];this.LP=this.N=this.Qs=this.Gv=null;this.D=0;this.gT=new g.LN(function(){},Y.ag.W2?4E3:3E3);
g.v(this,this.gT);this.kz=new g.LN(function(){});
g.v(this,this.kz);this.i$=new hpS(Y,function(L,T,I,B,m,G){Pn(V,L,T,I,B,m,G)});
this.Y=new g.Z({G:"div",U:"iv-drawer",J:{id:"iv-drawer"},B:[{G:"div",U:"iv-drawer-header",J:{"aria-role":"heading"},B:[{G:"span",U:"iv-drawer-header-text"},{G:"button",hT:["iv-drawer-close-button","ytp-button"],J:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",U:"iv-drawer-content"}]});g.v(this,this.Y);this.S=this.Y.element;this.OI=new g.Mb(this.Y,330);g.v(this,this.OI);this.T5=g.fB("iv-drawer-header-text",this.S);this.T=g.fB("iv-drawer-content",this.S);this.addCueRange(0,Y.videoData.lengthSeconds*
1E3,"",function(){V.l8&&Hn(V,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(V.l8=V.L)&&f_(V)});
this.y_=new g.Cc(this);g.v(this,this.y_);this.C.addEventListener("videodatachange",this.pc.bind(this))},dg_=function(r,D){D=D.data;
D.autoOpenMs&&r.addCueRange(D.autoOpenMs,0x8000000000000,"",function(){Hn(r,"YOUTUBE_DRAWER_AUTO_OPEN")});
D.autoCloseMs&&r.addCueRange(D.autoCloseMs,0x8000000000000,"",function(){f_(r)});
var Y=D.headerText;g.MF(r.T5,Y);r.K&&r.K.setAttribute("title",Y);D.eventId&&(r.eventId=D.eventId);r.Gv=g.K0(D.trackingParams);r.N=g.K0(D.closeTrackingParams);r.Qs=g.K0(D.iconTrackingParams)},S1r=function(r,D){var Y=D.cardId?D.cardId:"cr:"+r.D,V=r.C.Z().experiments.X2("enable_error_corrections_infocard_web_client");
if(!D.content&&D.teaser.simpleCardTeaserRenderer&&V){var L=D.teaser.simpleCardTeaserRenderer,T=D.icon?D.icon.infoCardIconRenderer:null;D={id:Y,timestamp:r.D,type:"simple",teaserText:g.Am(L.message),teaserDurationMs:Number(D.cueRanges[0].teaserDurationMs),startMs:Number(D.cueRanges[0].startCardActiveMs),autoOpen:!!D.autoOpen,sessionData:{},sponsored:!1,tf:{},Yu:null,QB:L.trackingParams?g.K0(L.trackingParams):null,Qs:T&&T.trackingParams?g.K0(T.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
KN:null,title:"",customMessage:"",url:null,onClickCommand:L.onTapCommand||null};wW(r,D)}else{var I;if((I=D.content)==null?0:I.simpleCardContentRenderer){if(!D.cueRanges.length)return;T=(L=D.content)==null?void 0:L.simpleCardContentRenderer;L=D.teaser.simpleCardTeaserRenderer;var B=D.icon?D.icon.infoCardIconRenderer:null;D={id:Y,timestamp:r.D,type:"simple",teaserText:g.Am(L.message),teaserDurationMs:Number(D.cueRanges[0].teaserDurationMs),startMs:Number(D.cueRanges[0].startCardActiveMs),autoOpen:!!D.autoOpen,
sessionData:rp(r,Y,D,T),sponsored:!1,tf:n_(T,L,T.command),Yu:T.trackingParams?g.K0(T.trackingParams):null,QB:L.trackingParams?g.K0(L.trackingParams):null,Qs:B&&B.trackingParams?g.K0(B.trackingParams):null,imageUrl:DB(T.image.thumbnails,290).url,displayDomain:T.displayDomain?g.Am(T.displayDomain):null,showLinkIcon:!!T.showLinkIcon,KN:null,title:T.title?g.Am(T.title):"",customMessage:T.callToAction?g.Am(T.callToAction):"",url:g.e(T.command,g.Z5).url?cn({pause_on_navigation:!r.context.videoData.isLivePlayback,
target:"new",value:g.e(T.command,g.Z5).url}):null,onClickCommand:null};wW(r,D)}else{var m;if((m=D.content)==null?0:m.collaboratorInfoCardContentRenderer){if(!D.cueRanges.length)return;L=(T=D.content)==null?void 0:T.collaboratorInfoCardContentRenderer;T=D.teaser.simpleCardTeaserRenderer;B=D.icon?D.icon.infoCardIconRenderer:null;D={id:Y,timestamp:r.D,type:"collaborator",teaserText:g.Am(T.message),teaserDurationMs:Number(D.cueRanges[0].teaserDurationMs),startMs:Number(D.cueRanges[0].startCardActiveMs),
autoOpen:!!D.autoOpen,sessionData:rp(r,Y,D,L),sponsored:!1,tf:n_(L,T,L.endpoint),Yu:L.trackingParams?g.K0(L.trackingParams):null,QB:T.trackingParams?g.K0(T.trackingParams):null,Qs:B&&B.trackingParams?g.K0(B.trackingParams):null,channelId:g.e(L.endpoint,g.J4).browseId,customMessage:L.customText?g.Am(L.customText):null,profileImageUrl:DB(L.channelAvatar.thumbnails,290).url,title:L.channelName?g.Am(L.channelName):"",metaInfo:[L.subscriberCountText?g.Am(L.subscriberCountText):""],url:cn({pause_on_navigation:!r.context.videoData.isLivePlayback,
target:"new",value:g.e(L.endpoint,g.J4).canonicalBaseUrl?g.e(L.endpoint,g.J4).canonicalBaseUrl:"/channel/"+g.e(L.endpoint,g.J4).browseId}),onClickCommand:null};wW(r,D)}else{var G;if((G=D.content)==null?0:G.playlistInfoCardContentRenderer){if(!D.cueRanges.length)return;L=(B=D.content)==null?void 0:B.playlistInfoCardContentRenderer;T=D.teaser.simpleCardTeaserRenderer;B=D.icon?D.icon.infoCardIconRenderer:null;D={id:Y,timestamp:r.D,type:"playlist",teaserText:g.Am(T.message),teaserDurationMs:Number(D.cueRanges[0].teaserDurationMs),
startMs:Number(D.cueRanges[0].startCardActiveMs),autoOpen:!!D.autoOpen,sessionData:rp(r,Y,D,L),sponsored:!1,tf:n_(L,T,L.action),Yu:L.trackingParams?g.K0(L.trackingParams):null,QB:T.trackingParams?g.K0(T.trackingParams):null,Qs:B&&B.trackingParams?g.K0(B.trackingParams):null,JB:DB(L.playlistThumbnail.thumbnails,258).url,customMessage:L.customMessage?g.Am(L.customMessage):null,playlistVideoCount:g.Am(L.playlistVideoCount),title:L.playlistTitle?g.Am(L.playlistTitle):"",metaInfo:[L.channelName?g.Am(L.channelName):
"",L.videoCountText?g.Am(L.videoCountText):""],url:cn({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:Rp5(L.action)}),onClickCommand:null};wW(r,D)}else{var M;if((M=D.content)==null?0:M.videoInfoCardContentRenderer){if(!D.cueRanges.length)return;var Q;L=(Q=D.content)==null?void 0:Q.videoInfoCardContentRenderer;T=D.teaser.simpleCardTeaserRenderer;B=D.icon?D.icon.infoCardIconRenderer:null;D={id:Y,timestamp:r.D,type:"video",teaserText:g.Am(T.message),teaserDurationMs:Number(D.cueRanges[0].teaserDurationMs),
startMs:Number(D.cueRanges[0].startCardActiveMs),autoOpen:!!D.autoOpen,sessionData:rp(r,Y,D,L),sponsored:!1,tf:n_(L,T,L.action),Yu:L.trackingParams?g.K0(L.trackingParams):null,QB:T.trackingParams?g.K0(T.trackingParams):null,Qs:B&&B.trackingParams?g.K0(B.trackingParams):null,JB:DB(L.videoThumbnail.thumbnails,258).url,videoDuration:L.lengthString?g.Am(L.lengthString):null,customMessage:L.customMessage?g.Am(L.customMessage):null,title:L.videoTitle?g.Am(L.videoTitle):"",metaInfo:[L.channelName?g.Am(L.channelName):
"",L.viewCountText?g.Am(L.viewCountText):""],isLiveNow:!!L.badge,url:cn({pause_on_navigation:!r.context.videoData.isLivePlayback,target:"new",value:Rp5(L.action)}),onClickCommand:null};wW(r,D)}}}}}r.D++},DB=function(r,D){for(var Y=-1,V=-1,L=0;L<r.length;L++){if(r[L].height===D||r[L].width===290)return r[L];
((r[L].height||0)<D||(r[L].width||0)<290)&&(Y<0||(r[Y].height||0)<(r[L].height||0)||(r[Y].width||0)<(r[L].width||0))?Y=L:((r[L].height||0)>=D||(r[L].width||0)>=290)&&(V<0||(r[V].height||0)>(r[L].height||0)||(r[V].width||0)>(r[L].width||0))&&(V=L)}return r[V>=0?V:Y]},rp=function(r,D,Y,V){return{feature:Y.feature?Y.feature:"cards",
src_vid:r.context.videoData.videoId,annotation_id:D,ei:r.context.videoData.eventId||"",itct:V.trackingParams||""}},vCS=function(r,D){if(D=Ng_(r,D))D===r.W&&(r.W=null),r.C.removeCueRange(D.O7.id),g.mJ(D.T$),g.wT(r.cards,D),r.C9(),YI(r)},Hn=function(r,D,Y){if(!r.L){r.OI.show();
r.u$=new g.LN(function(){g.yO(r.context.C.getRootNode(),g.fH.IV_DRAWER_OPEN)},0);
r.u$.start();r.y_.X(r.T,"mousewheel",function(I){r.gT.start();I.preventDefault();I=I||window.event;var B=0;I.type=="MozMousePixelScroll"?B=0==(I.axis==I.HORIZONTAL_AXIS)?I.detail:0:window.opera?B=I.detail:B=I.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?I.wheelDeltaY/-30:I.wheelDeltaY/-1.2:I.wheelDelta/-1.6:I.wheelDeltaY/-3;if(I=B)r.T.scrollTop+=I});
r.L=!0;var V=g.Rp();V&&r.Gv&&r.N&&g.j$(V,[r.Gv,r.N]);D={TRIGGER_TYPE:D};for(var L=g.F(r.cards),T=L.next();!T.done;T=L.next())T=T.value,T.gi||(T.gi=!0,buW(r.context.logger,T.O7.tf.Tg,D)),V&&g.j$(V,[T.O7.Yu]);Om(r.C);Y&&(r.j=new g.LN(function(){r.rT=r.K;r.Bo.focus()},330),r.j.start())}},f_=function(r){r.L&&(r.OI.hide(),g.Nj(r.y_),g.Wf(r.context.C.getRootNode(),g.fH.IV_DRAWER_OPEN),r.L=!1,Om(r.C),r.j&&r.j.stop(),r.j=new g.LN(function(){r.rT&&(r.rT.focus(),r.rT=null)},330),r.j.start())},epS=function(r){g.ax(r.gD(),
[g.fH.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.NI(r.C,r.S,5);r.f9();r.K=g.fB("ytp-cards-button",r.C.getRootNode());r.Bo=g.fB("iv-drawer-close-button",r.S);r.isInitialized=!0},cRa=function(r){r.Tv.push(g.yg("iv-teaser-shown",r.xB,r));
r.Tv.push(g.yg("iv-teaser-hidden",r.MPI,r));r.Tv.push(g.yg("iv-teaser-clicked",r.SA,r));r.z5=!0},Cnx=function(r,D){var Y;
return D.onClickCommand&&((Y=g.e(D.onClickCommand,g.UM_))==null?void 0:Y.targetId)==="engagement-panel-error-corrections"?(r.LP=D,!0):!1},Zur=function(r,D){r.LP=D;
var Y=r.C.getVideoData();if(!Y)return!1;Y=g.KX(Y);if(Y==null?0:Y.markersMap)for(var V,L=0;((V=Y)==null?void 0:V.markersMap.length)>L;L++){var T=void 0,I=(T=Y)==null?void 0:T.markersMap[L];if(I.key==="ERROR_CORRECTION_MARKERS"&&(T=void 0,(I=(T=I.value)==null?void 0:T.markers)&&I.length>0))return V=void 0,D.startMs=((V=g.e(I[0],g.VqP))==null?void 0:V.timeRangeStartMillis)||0,r.LP=null,!0}return!1},wW=function(r,D){if(!Cnx(r,D)||Zur(r,D)){var Y=XrR(r,D);
if(Y){var V={O7:D,T$:Y.element,gi:!1};if(D.onClickCommand)r.C.V("web_infocards_teaser_show_logging_fix")&&(r.z5||cRa(r),vCS(r,D.id),Y=r.findLastIndex(V),g.IJ(r.cards,Y,0,V));else{r.isInitialized||epS(r);vCS(r,D.id);var L=r.findLastIndex(V);g.IJ(r.cards,L,0,V);Y.CP(r.T,L);r.C9()}D.autoOpen?r.addCueRange(D.startMs,0x8000000000000,D.id,function(){r.L||(r.W=V,YI(r),oCc(r,V),Hn(r,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(Y=r.context.C.getCurrentTime()*1E3,Y<5E3&&Y>D.startMs&&Pn0(r,V),r.addCueRange(D.startMs,
D.startMs+1,D.id,function(){Pn0(r,V)}),YI(r))}}},XrR=function(r,D){switch(D.type){case "simple":r=r.i$;
var Y=D.displayDomain?{G:"div",U:"iv-card-image-text",SD:D.displayDomain}:void 0;var V=JR0(D);Y={G:"div",hT:["iv-card"],B:[{G:"a",U:"iv-click-target",J:{href:D.url?eq(D.url)||"":""},B:[ZQ(D.imageUrl,Y),{G:"div",U:"iv-card-content",B:[C_("h2",void 0,D.title),V]}]}]};Y=new g.Z(Y);Xr(r,g.nB("iv-click-target",Y.element),D,D.url);D=Y;break;case "collaborator":r=r.i$;Y={G:"div",hT:["iv-card","iv-card-channel"],B:[{G:"a",hT:["iv-click-target"],J:{href:eq(D.url)||"","data-ytid":D.channelId},B:[ZQ(D.profileImageUrl),
{G:"div",U:"iv-card-content",B:[tsr(D),{G:"h2",U:"iv-card-primary-link",SD:D.title},iua(D)]}]}]};Y=new g.Z(Y);Xr(r,g.nB("iv-click-target",Y.element),D,D.url);D=Y;break;case "playlist":r=r.i$;Y={G:"div",hT:["iv-card","iv-card-playlist"],B:[{G:"a",U:"iv-click-target",J:{href:eq(D.url)||""},B:[ZQ(D.JB,{G:"div",U:"iv-card-image-overlay",B:[{G:"span",U:"iv-card-playlist-video-count",SD:D.playlistVideoCount}]}),{G:"div",U:"iv-card-content",B:[tsr(D),C_("h2","iv-card-primary-link",D.title),iua(D)]}]}]};
Y=new g.Z(Y);Xr(r,g.nB("iv-click-target",Y.element),D,D.url);D=Y;break;case "productListing":r=r.i$;var L=D.offers.length!=0;Y=["iv-card"];V="";var T=JR0(D);L&&(Y.push("iv-card-product-listing"),V="iv-card-primary-link",T=D.offers[0],L=[],T.price&&L.push({G:"div",U:"iv-card-offer-price",SD:T.price}),T.merchant&&L.push({G:"div",U:"iv-card-offer-merchant",SD:T.merchant}),T={G:"div",B:L});L=D.url?eq(D.url)||"":"";Y={G:"div",hT:Y,J:{tabindex:"0"},B:[{G:"a",hT:["iv-card-image","iv-click-target"],J:{style:"background-image: url("+
D.imageUrl+");",href:L,"aria-hidden":"true",tabindex:"-1"}},{G:"div",U:"iv-card-content",B:[D.sponsored?{G:"div",U:"iv-card-sponsored",B:["Sponsored",{G:"div",U:"iv-ad-info-container",B:[{G:"div",U:"iv-ad-info",SD:"{{adInfo}}"},{G:"div",U:"iv-ad-info-icon-container",B:[{G:"div",U:"iv-ad-info-icon"},{G:"div",U:"iv-ad-info-callout"}]}]}]}:"",{G:"a",U:"iv-click-target",J:{href:L},B:[C_("h2",V,D.title),T]}]}]};Y=new g.Z(Y);V=g.Li("span");g.MF(V,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
Y.JC(V,"adInfo");Xr(r,g.nB("iv-click-target",Y.element),D,D.url);D=Y;break;case "video":r=r.i$;V=D.videoDuration?{G:"span",U:"iv-card-video-duration",SD:D.videoDuration}:void 0;T=D.isLiveNow?{G:"span",hT:["yt-badge","yt-badge-live"],SD:"LIVE NOW"}:null;L={G:"div",hT:["iv-card","iv-card-video"],B:[{G:"a",U:"iv-click-target",J:{href:((Y=D.url)==null?void 0:eq(Y))||""},B:[ZQ(D.JB,V),{G:"div",U:"iv-card-content",B:[tsr(D),C_("h2","iv-card-primary-link",D.title),iua(D),T]}]}]};Y=new g.Z(L);Xr(r,g.nB("iv-click-target",
Y.element),D,D.url);D=Y;break;default:return null}return D},nC_=function(r){if(r.W)return r.W.O7.type==="productListing";
if(r.C.V("enable_wn_infocards")){var D;return!((D=r.cards)==null||!D.length)&&g.EG(r.cards,function(Y){return Y.O7.type==="productListing"})}return g.EG(r.cards,function(Y){return Y.O7.type==="productListing"})},YI=function(r){g.Fw(r.C.getRootNode(),"ytp-cards-shopping-active",nC_(r))},Pn0=function(r,D){if(!g.s3(r.C.getRootNode(),"ytp-cards-teaser-shown")){if(r.W!==D){var Y=g.Rp(),V=r.W?r.W.O7.Qs:r.Qs;
Y&&V&&g.QE(Y,[V]);r.W=D;YI(r)}(Y=r.isInitialized&&r.gD().style.display=="none")||(Y=r.context.C.getPlayerState(),V=Y===0&&r.context.C.getCurrentTime()===0,Y=!(Y===1||Y===3||V));Y||D.O7.teaserDurationMs&&r.C.e9(!0,{teaserText:D.O7.teaserText,durationMs:D.O7.teaserDurationMs,onClickCommand:D.O7.onClickCommand});r.kz.isActive()||((!r.L||!r.gT.isActive()&&r.eD)&&oCc(r,D),r.kz.start(910+D.O7.teaserDurationMs))}},oCc=function(r,D){r.Y.Pk?(D=new Jj([0,
r.T.scrollTop],[0,D.T$.offsetTop],600,Y15),r.context.L.listen(D,"animate",function(Y){r.T.scrollTop=Y.y}),r.context.L.listen(D,"finish",function(Y){r.T.scrollTop=Y.y}),D.play()):(r.Y.fC(!0),r.T.scrollTop=D.T$.offsetTop,r.Y.fC(!1))},VP=function(r){return r.W&&r.W.O7?r.W.O7:r.cards[0]&&r.cards[0].O7?r.cards[0].O7:null},Ng_=function(r,D){return g.PS(r.cards,function(Y){return Y.O7.id===D})},Lv=function(r,D,Y){oH.call(this,r,D);
this.annotation=Y;this.isActive=!1},Hua=function(r){var D=r.annotation.data;
"start_ms"in D&&"end_ms"in D&&r.addCueRange(Number(D.start_ms),Number(D.end_ms),r.annotation.id,function(){r.show()},function(){r.hide()})},TV=function(r,D,Y){Lv.call(this,r,D,Y);
this.T=null;this.N=!1;this.L=null;this.S=!1;this.W=this.D=this.j=null},flW=function(r,D){var Y=Y===void 0?0:Y;
var V=X0r(D).width;g.$O(D,V);Y=new rRe(D,[V,D.offsetTop],[V-V-Y,D.offsetTop],200,DgR);g.v(r,Y);r.context.L.listen(Y,"begin",function(){g.Ef(D,!0)});
Y.play()},DEq=function(r,D){if(D.channel_name){var Y=r.createElement({G:"div",
hT:["iv-branding-context-name"],SD:D.channel_name}),V=r.createElement({G:"div",hT:["iv-branding-context-subscribe"]}),L=D.standalone_subscribe_button_data;L&&(r.W=new g.re(L.subscribeText,L.subscribeCount,L.unsubscribeText,L.unsubscribeCount,!!L.enabled,!!L.classic,D.channel_id,!!L.subscribed,L.feature,D.session_data.itct,r.context.C,!1),r.W.CP(V));var T=r.createElement({G:"div",hT:["iv-branding-context-subscribe-caret"]}),I=r.createElement({G:"div",hT:["branding-context-container-inner"]});I.appendChild(T);
I.appendChild(Y);I.appendChild(V);g.Ef(I,!1);var B=r.createElement({G:"div",hT:["branding-context-container-outer"]});B.appendChild(I);g.Uf(B,"right",D.image_width+"px");g.IG(r.gD(),B);r.L=new g.LN(function(){wrS(r,I,B)},500);
g.v(r,r.L);r.context.W.listen(r.gD(),"mouseover",function(){rUq(r,I,B,T,D.image_height)});
r.context.W.listen(r.gD(),"mouseout",function(){r.L.start()})}},rUq=function(r,D,Y,V,L){r.L.stop();
if(!r.S){var T=g.lc(D);r.W||(D.style.width=g.gd(T.width,!0),Y.style.width=g.gd(T.width,!0));g.Uf(V,"top",T.height-Math.max(Math.min(T.height,L)/2+10,20)+"px");g.Uf(V,"right","1px");r.S=!0;g.Ef(D,!0);r.j=new g.LN(function(){g.yO(this.gD(),"iv-branding-active")},0,r);
r.j.start()}},wrS=function(r,D,Y){g.Wf(r.gD(),"iv-branding-active");
r.D=new g.LN(function(){g.Ef(D,!1);r.W||(Y.style.width=g.gd(0,!0))},250);
r.D.start();r.S=!1},YPr=function(r,D,Y,V,L,T,I){this.W=r;
this.L=D;this.ag=Y;this.videoData=V;this.logger=L;this.C=T;this.T=I},VQS=function(r,D,Y){Lv.call(this,r,D,Y);
var V=this;this.K=this.isCollapsed=this.Y=!1;this.D=5E3;this.T=this.L=this.W=this.S=null;this.N=this.createElement({G:"div",hT:["iv-promo-contents"]});this.j=new g.LN(function(){V.W.setAttribute("aria-hidden","true");g.Ef(V.L,!1);g.Ef(V.T,!0)},700,this);
g.v(this,this.j)},TIM=function(r){var D=r.annotation.data;
if(r.annotation.style==="cta")var Y=6;else if(r.annotation.style==="video"||r.annotation.style==="playlist")Y=7;r.D=D.collapsedelay_ms||r.D;var V=["iv-promo","iv-promo-inactive"];r.gD().setAttribute("aria-hidden","true");r.gD().setAttribute("aria-label","Promotion");r.gD().tabIndex=0;var L=r.annotation.HY(),T=D.image_url;if(T){var I=r.createElement({G:"div",hT:["iv-promo-img","iv-click-target"]});T=r.createElement({G:"img",J:{src:T,"aria-hidden":"true"}});I.appendChild(T);D.video_duration&&!D.is_live?
(T=r.createElement({G:"span",U:"iv-promo-video-duration",SD:D.video_duration}),I.appendChild(T)):D.playlist_length&&(T=r.createElement({G:"span",U:"iv-promo-playlist-length",SD:D.playlist_length.toString()}),I.appendChild(T));L&&Pn(r,I,L,r.annotation.id,D.session_data,void 0,Y)}L?(T=r.createElement({G:"a",U:"iv-promo-txt"}),g.Ss(T,eq(L)),r.W=T):r.W=r.createElement({G:"div",U:"iv-promo-txt"});switch(r.annotation.style){case "cta":case "website":var B=r.createElement({G:"p",B:[{G:"strong",SD:D.text_line_1}]});
var m=r.createElement({G:"p",B:[{G:"span",U:"iv-promo-link",SD:D.text_line_2}]});if(T=D.text_line_3){V.push("iv-promo-website-card-cta-redesign");var G=r.createElement({G:"button",hT:["iv-promo-round-expand-icon","ytp-button"]});T=r.createElement({G:"button",hT:["iv-button","iv-promo-button"],B:[{G:"span",U:"iv-button-content",SD:T}]});var M=r.createElement({G:"div",U:"iv-promo-button-container"});M.appendChild(T);L&&Pn(r,r.gD(),L,r.annotation.id,D.session_data,void 0,Y)}g.yO(r.W,"iv-click-target");
L&&Pn(r,r.W,L,r.annotation.id,D.session_data,void 0,Y);break;case "playlist":case "video":B=r.createElement({G:"p",B:[{G:"span",SD:D.text_line_1}]}),m=r.createElement({G:"p",B:[{G:"strong",SD:D.text_line_2}]}),D.is_live&&(B=m,m=r.createElement({G:"span",hT:["yt-badge","iv-promo-badge-live"],SD:"LIVE NOW"})),g.yO(r.W,"iv-click-target"),L&&Pn(r,r.W,L,r.annotation.id,D.session_data,void 0,Y),V.push("iv-promo-video")}B&&r.W.appendChild(B);m&&r.W.appendChild(m);r.N.appendChild(r.W);M&&r.N.appendChild(M);
Y=r.createElement({G:"div",U:"iv-promo-actions"});r.T=r.createElement({G:"button",hT:["iv-promo-expand","ytp-button"]});r.T.title="Expand";r.context.W.listen(r.T,"click",function(Q){LIR(r,5E3,Q)});
Y.appendChild(r.T);g.Ef(r.T,!1);r.context.W.listen(r.gD(),"mouseover",r.yTz,r);r.context.W.listen(r.gD(),"mouseout",r.HPv,r);r.context.W.listen(r.gD(),"touchend",function(Q){LIR(r,5E3,Q)});
r.L=r.createElement({G:"button",hT:["iv-promo-close","ytp-button"]});r.L.title="Close";r.context.W.listen(r.L,"click",r.annotation.style==="cta"&&D.text_line_3?r.eYF:r.hYo,r);Y.appendChild(r.L);g.ax(r.gD(),V);I&&(g.IG(r.gD(),I),G&&I.appendChild(G));g.IG(r.gD(),r.N);g.IG(r.gD(),Y)},LIR=function(r,D,Y){Y.stopPropagation();
IPc(r);xE_(r,D);r.W.focus()},BIW=function(r){r.isCollapsed||r.K||r.S||(g.yO(r.gD(),"iv-promo-collapsed"),r.isCollapsed=!0,r.j.start())},IPc=function(r){r.j.stop();
r.isCollapsed&&(g.U3(r.gD(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),r.isCollapsed=!1,r.W&&r.W.removeAttribute("aria-hidden"),g.Ef(r.T,!1),g.Ef(r.L,!0))},xE_=function(r,D){r.S||(r.S=g.Jo(function(){mE_(this);
BIW(this)},D,r))},mE_=function(r){r.S&&(g.vW.clearTimeout(r.S),r.S=null)},Glr=function(r){this.C=r},buW=function(r,D,Y){D&&(Y?Il(r,D.map(function(V){return g.Sb(V,Y)})):Il(r,D))},Il=function(r,D,Y,V){var L=1,T=void 0,I=-1;
if(Y){var B=!1;T=function(){L--;L||B||(clearTimeout(I),B=!0,Y())};
I=setTimeout(function(){B=!0;Y()},1E3)}D=g.F(D||[]);
for(var m=D.next();!m.done;m=D.next())m=m.value,L++,g.Hh(m,T);V&&(L++,V!==0&&r.C.sendVideoStatsEngageEvent(V,T))},MQ_=function(r){g.uF.call(this,r);
var D=this;this.Tv=this.K=!1;this.loadNumber=0;this.D={};this.logger=new Glr(this.player);this.S=new g.Cc(this);this.j=this.N=null;this.events=new g.Cc(this);this.xx=this.Y=this.W=null;this.LP=[];g.v(this,this.S);this.S.X(this.player,"onVideoAreaChange",function(){D.publish("onVideoAreaChange")});
this.S.X(this.player,"onHideControls",function(){D.publish("onHideControls")});
this.S.X(this.player,"onShowControls",function(){D.publish("onShowControls")});
this.S.X(this.player,"resize",function(V){D.publish("resize",V)});
this.S.X(this.player,"presentingplayerstatechange",function(V){D.publish("presentingplayerstatechange",V)});
this.subscribe("presentingplayerstatechange",this.ij,this);this.subscribe("resize",this.HE,this);this.player.Z().rT.subscribe("vast_info_card_add",this.H3,this);g.v(this,this.events);this.i$=this.createElement({G:"div",U:"video-custom-annotations"});this.T=new g.Z({G:"div",hT:["ytp-player-content","ytp-iv-player-content"]});g.v(this,this.T);g.NI(this.player,this.T.element,4);this.T.hide();this.L=new g.Z({G:"div",hT:["ytp-iv-video-content"]});g.v(this,this.L);r=this.createElement({G:"div",U:"video-annotations"});
r.appendChild(this.i$);this.L.element.appendChild(r);this.C4()&&this.load();var Y=this.createElement({G:"style"});(g.PJ("HEAD")[0]||document.body).appendChild(Y);this.addOnDisposeCallback(function(){g.mJ(Y)});
if(r=Y.sheet)r.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),r.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),r.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),r.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),r.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),r.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),r.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),r.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),r.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),r.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},j8c=function(r){r=r.createElement({G:"div",
hT:["annotation","annotation-type-custom"]});g.Ef(r,!1);return r},Q8q=function(r,D){D=!D.isCued()&&!g.X(D,1024);
r.T.fC(D);r.L.fC(D)},s8T=function(r,D,Y){r.K=!0;
r.j=g.EA(D,Y)},yUa=function(r,D){for(var Y={},V=g.F(D.attributes),L=V.next();!L.done;L=V.next())L=L.value,Y[L.name]=L.nodeValue;
for(V=0;V<D.childNodes.length;V++)if(L=D.childNodes[V],g.PW(L)&&L.nodeType==1){if(Y[L.tagName])var T=Y[L.tagName];else if(L.tagName==="data"){L.childNodes.length>0&&(T=L.childNodes[0].nodeValue,Y[L.tagName]=typeof T==="string"?T.trim():T);continue}else T=[],Y[L.tagName]=T;L&&L.tagName==="TEXT"?L.childNodes.length===1&&L.childNodes[0].nodeType===3?T.push(L.childNodes[0].nodeValue):T.push(""):L&&T.push(yUa(r,L))}return Y},FI0=function(r){var D=r.player.getVideoData();
if(D.UI){var Y=r.player.Z().rT.get(D.videoId);if(Y){var V={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(L,T,I){L=r.loadNumber;T=D.videoId;r.loaded&&r.loadNumber===L&&r.player.getVideoData().videoId===T&&(I=g.gX(I)&&I.responseXML?I.responseXML:null)&&aPe(r,I)}};
g.MK()&&(V.onFinish=WIr(r,V.onFinish));V.postParams={ic_only:"1"};UE_(V,Y);r.K=!0;g.EA(D.UI,V)}}},UE_=function(r,D){r.method="POST";
r.postParams=r.postParams||{};D.eK&&(r.postParams.ic_coll=D.eK);D.LF&&(r.postParams.ic_xml=D.LF);D.F$&&(r.postParams.ic_track=D.F$)},uDq=function(r){var D=new g.Z({G:"div"});
g.Ef(D.element,!1);var Y=new zpe(r.player,D.element,xI(r));g.v(Y,D);D.CP(r.T.element);Y.nk();return Y},kla=function(r,D){var Y,V;
if(D=(Y=D.getWatchNextResponse())==null?void 0:(V=Y.cards)==null?void 0:V.cardCollectionRenderer)r.Tv=!0,qPx(r,D),D.headerText&&r.xx&&(Y=g.Am(D.headerText),r.xx.setAttribute("title",Y))},xI=function(r){if(!r.Y){var D=new VsR(r);
g.v(r,D);var Y=new g.JW(r);g.v(r,Y);r.Y=new YPr(D,Y,r.player.Z(),r.player.getVideoData(),r.logger,r.player,r.Og)}return r.Y},aPe=function(r,D){var Y=!1,V=D.getElementsByTagName("annotations");
if(V&&!(V.length<1)&&(V=V[0].getAttribute("itct"))){var L=g.Rp();if(L){var T=g.Ed();T&&g.xL(g.YZ)(void 0,L,T,[g.K0(V)])}}D=D.getElementsByTagName("annotation");for(V=0;V<D.length;V++){T=yUa(r,D[V]);L=null;try{if(T){var I=T.id,B=/.+/;var m=typeof I==="string"&&B!=null&&I!=null&&I.match(B)?I:"";var G=bp(T.type,gHr),M=bp(T.style,$Er),Q=Fvq(T.data),y=Q.length!==0?JSON.parse(Q):{};var a=T.action;T=ARr;if(a==null)var W=null;else if(g.oo(a)){B=[];for(var q=g.F(a),A=q.next();!A.done;A=q.next()){var p=T(A.value);
p&&B.push(p)}W=B}else{var t=T(a);W=t?[t]:[]}L=m&&G?new OuT(m,G,M,W,y):null}else L=null}catch(Ly){}if(L)if(L.type==="branding"||L.type==="promotion"){T=r;B=L;var l=j8c(T),d=null;switch(B.type){case "branding":if(T.player.Z().OQ)break;T.T.element.appendChild(l);d=new TV(l,xI(T),B);break;case "promotion":g.NI(T.player,l,4),d=new VQS(l,xI(T),B)}d&&d.nk();if(T=d)g.v(r,T),r.D[L.id]=T}else if(L.type==="card"||L.type==="drawer"){r.W||(r.W=uDq(r),g.v(r,r.W));if(L.type==="card"){l=r.W;var b=(Y=L)&&Y.data&&
Y.data.card_type;L=Y.data;if(b)switch(T=L.tracking||{},T={Tg:T.impression,click:T.click,close:T.close,vO:T.teaser_impression,f$:T.teaser_click},B=L.tracking_params||{},d=null,b){case "collaborator":Y={id:Y.id,timestamp:L.timestamp||0,type:L.card_type,teaserText:L.teaser_text,teaserDurationMs:L.teaser_duration_ms,startMs:L.start_ms,autoOpen:L.auto_open||!1,sessionData:L.session_data||{},sponsored:L.sponsored||!1,tf:T,Yu:B.card?g.K0(B.card):null,QB:B.teaser?g.K0(B.teaser):null,Qs:B.icon?g.K0(B.icon):
null,channelId:L.channel_id,customMessage:L.custom_message?L.custom_message:null,profileImageUrl:L.image_url,title:L.title,metaInfo:L.meta_info,url:cn({pause_on_navigation:L.pause_on_navigation,target:L.target||"new",value:L.url}),onClickCommand:null};wW(l,Y);break;case "playlist":Y={id:Y.id,timestamp:L.timestamp||0,type:L.card_type,teaserText:L.teaser_text,teaserDurationMs:L.teaser_duration_ms,startMs:L.start_ms,autoOpen:L.auto_open||!1,sessionData:L.session_data||{},sponsored:L.sponsored||!1,tf:T,
Yu:B.card?g.K0(B.card):null,QB:B.teaser?g.K0(B.teaser):null,Qs:B.icon?g.K0(B.icon):null,JB:L.image_url,playlistVideoCount:L.playlist_video_count,customMessage:L.custom_message?L.custom_message:null,title:L.title,metaInfo:L.meta_info,url:cn({pause_on_navigation:L.pause_on_navigation,target:L.target||"new",value:L.url}),onClickCommand:null};wW(l,Y);break;case "productListing":L.signin_url&&(d=cn({target:"current",value:L.signin_url}));b=[];for(var n=L.offers||[],P=0;P<n.length;P++)b.push(new Kvq(g.VN(n[P].merchant),
g.VN(n[P].price)));Y={id:Y.id,timestamp:L.timestamp||0,type:L.card_type,teaserText:L.teaser_text,teaserDurationMs:L.teaser_duration_ms,startMs:L.start_ms,autoOpen:L.auto_open||!1,sessionData:L.session_data||{},sponsored:L.sponsored||!1,tf:T,Yu:B.card?g.K0(B.card):null,QB:B.teaser?g.K0(B.teaser):null,Qs:B.icon?g.K0(B.icon):null,imageUrl:L.image_url,displayDomain:L.display_domain?L.display_domain:null,showLinkIcon:!!L.show_link_icon,KN:L.button_icon_url?L.button_icon_url:null,title:L.title,customMessage:L.custom_message?
L.custom_message:null,url:cn({pause_on_navigation:L.pause_on_navigation,target:L.target||"new",value:L.url}),Z_g:d,ke$:L.signin_title?L.signin_title:void 0,Q7z:L.signin_message?L.signin_message:void 0,offers:b,onClickCommand:null};wW(l,Y);break;case "simple":Y={id:Y.id,timestamp:L.timestamp||0,type:L.card_type,teaserText:L.teaser_text,teaserDurationMs:L.teaser_duration_ms,startMs:L.start_ms,autoOpen:L.auto_open||!1,sessionData:L.session_data||{},sponsored:L.sponsored||!1,tf:T,Yu:B.card?g.K0(B.card):
null,QB:B.teaser?g.K0(B.teaser):null,Qs:B.icon?g.K0(B.icon):null,imageUrl:L.image_url,displayDomain:L.display_domain?L.display_domain:null,showLinkIcon:!!L.show_link_icon,KN:L.button_icon_url?L.button_icon_url:null,title:L.title,customMessage:L.custom_message?L.custom_message:null,url:cn({pause_on_navigation:L.pause_on_navigation,target:L.target||"new",value:L.url}),onClickCommand:null};wW(l,Y);break;case "video":Y={id:Y.id,timestamp:L.timestamp||0,type:L.card_type,teaserText:L.teaser_text,teaserDurationMs:L.teaser_duration_ms,
startMs:L.start_ms,autoOpen:L.auto_open||!1,sessionData:L.session_data||{},sponsored:L.sponsored||!1,tf:T,Yu:B.card?g.K0(B.card):null,QB:B.teaser?g.K0(B.teaser):null,Qs:B.icon?g.K0(B.icon):null,JB:L.image_url,videoDuration:L.video_duration||null,customMessage:L.custom_message?L.custom_message:null,title:L.title,metaInfo:L.meta_info,isLiveNow:!!L.is_live_now,url:cn({pause_on_navigation:L.pause_on_navigation,target:L.target||"new",value:L.url}),onClickCommand:null},wW(l,Y)}}else dg_(r.W,L);Y=!0}}Y&&
(Om(r.player),r.HE())},qPx=function(r,D){var Y=!1;
r.W||(r.W=uDq(r),g.v(r,r.W));for(var V=g.F(D.cards||[]),L=V.next();!L.done;L=V.next())L=L.value,L.cardRenderer&&(S1r(r.W,L.cardRenderer),Y=!0);if(Y){var T;(T=r.player.getVideoData())!=null&&g.S7(T)||(Y=r.W,V=D.headerText?g.Am(D.headerText):"",g.MF(Y.T5,V),Y.K&&Y.K.setAttribute("title",V),Y.context.videoData.eventId&&(Y.eventId=Y.context.videoData.eventId),Y.Gv=D.trackingParams?g.K0(D.trackingParams):null,Y.N=D.closeButton.infoCardIconRenderer.trackingParams?g.K0(D.closeButton.infoCardIconRenderer.trackingParams):
null,Y.Qs=D.icon.infoCardIconRenderer.trackingParams?g.K0(D.icon.infoCardIconRenderer.trackingParams):null,r.HE());Om(r.player)}},AUc=function(r,D,Y,V,L){if(!r.player.Z().OQ){var T=[];
D.navigationEndpoint&&g.e(D.navigationEndpoint,g.J4)&&g.e(D.navigationEndpoint,g.J4).browseId&&T.push(new kXS("openUrl","click",new uUx("/channel/"+g.e(D.navigationEndpoint,g.J4).browseId,"new",!0,!0)));var I=D.watermark.thumbnails[0];V={channel_name:D.channelName,end_ms:D.endTimeMs,image_height:I.height,image_type:1,image_url:I.url,image_width:I.width,is_mobile:!1,session_data:{annotation_id:Y,ei:L,feature:"iv",itct:D.trackingParams,src_vid:V},start_ms:D.startTimeMs};if(D.subscribeButton&&g.e(D.subscribeButton,
g.K9)){V.channel_id=g.e(D.subscribeButton,g.K9).channelId;var B;D=g.e(D.subscribeButton,g.K9);I=L=null;D.subscribed?(D.subscriberCountWithUnsubscribeText&&(L=g.Am(D.subscriberCountWithUnsubscribeText)),D.subscriberCountText&&(I=g.Am(D.subscriberCountText))):(D.subscriberCountText&&(L=g.Am(D.subscriberCountText)),D.subscriberCountWithSubscribeText&&(I=g.Am(D.subscriberCountWithSubscribeText)));var m,G=((m=g.e((B=D.signInEndpoint)==null?void 0:B.commandMetadata,g.FZ))==null?void 0:m.url)||"";B={subscribeText:g.Am(D.unsubscribedButtonText),
subscribeCount:L||"",unsubscribeText:g.Am(D.subscribedButtonText),unsubscribeCount:I||"",enabled:D.enabled||!1,classic:!1,subscribed:D.subscribed||!1,feature:"iv",signInUrl:G};V.standalone_subscribe_button_data=B}T=new OuT(Y,"branding","branding",T,V);B=j8c(r);r.T.element.appendChild(B);T=new TV(B,xI(r),T);T.nk();g.v(T,T);r.D[Y]=T}},WIr=function(r,D){return function(){var Y=g.Ja.apply(0,arguments);
r.DQ()||r.LP.push(g.P3.Nu(function(){D.apply(null,g.k(Y))}))}},OBr=function(r){return r==="annotation-editor"||r==="live-dashboard"};
g.JI.prototype.e9=g.Vo(45,function(r,D){var Y=g.Eg(this.FM());Y&&Y.e9(r,D)});
var hj={},tj=null;g.VW(Jj,g.u_);g.x=Jj.prototype;g.x.getDuration=function(){return this.duration};
g.x.play=function(r){if(r||this.W==0)this.progress=0,this.coords=this.T;else if(this.isPlaying())return!1;ip(this);this.startTime=r=g.D0();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.S=this.startTime;this.progress||this.PE();this.IW("play");this.isPaused()&&this.IW("resume");this.W=1;var D=g.HW(this);D in hj||(hj[D]=this);n7S();HVq(this,r);return!0};
g.x.stop=function(r){ip(this);this.W=0;r&&(this.progress=1);fwW(this,this.progress);this.onStop();this.uv()};
g.x.pause=function(){this.isPlaying()&&(ip(this),this.W=-1,this.IW("pause"))};
g.x.F2=function(){this.W==0||this.stop(!1);this.IW("destroy");Jj.tN.F2.call(this)};
g.x.destroy=function(){this.dispose()};
g.x.sO=function(){this.IW("animate")};
g.x.IW=function(r){this.dispatchEvent(new w0a(r,this))};
g.VW(w0a,g.NF);g.VW(K_,Jj);K_.prototype.L=function(){};
K_.prototype.sO=function(){this.L();K_.tN.sO.call(this)};
K_.prototype.uv=function(){this.L();K_.tN.uv.call(this)};
K_.prototype.PE=function(){this.L();K_.tN.PE.call(this)};
g.VW(rRe,K_);rRe.prototype.L=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.U(VsR,g.N);g.x=VsR.prototype;g.x.listen=function(r,D,Y,V){Y=(0,g.wQ)(Y,V||this.T);r=g.KK(r,D,Y);this.W.push(r);return r};
g.x.XF=function(r,D,Y,V){Y=(0,g.wQ)(Y,V||this.T);r=o7M(r,D,Y);this.W.push(r);return r};
g.x.G4=function(r){g.lK(r);g.wT(this.W,r)};
g.x.removeAll=function(){g.lK(this.W);this.W.length=0};
g.x.F2=function(){this.removeAll();g.N.prototype.F2.call(this)};g.U(IlW,g.uF);g.x=IlW.prototype;g.x.load=function(){g.uF.prototype.load.call(this);if(!RH(this)){var r=g.jdf(this.player.getVideoData());r?(r=Tge(r,xgS(this)),zS(this,r,!1)):BgT(this)}};
g.x.unload=function(){zS(this,null);this.S&&(this.S.abort(),this.S=null);g.uF.prototype.unload.call(this)};
g.x.f3=function(r,D){return RH(this)?r==="loadCustomEndscreenRenderer"?(r=Tge(D,"new"),zS(this,r),!0):null:null};
g.x.getOptions=function(){return RH(this)?["loadCustomEndscreenRenderer"]:[]};
g.x.QW=function(){if(this.endscreen&&this.endscreen.elements){var r=this.player.getVideoContentRect();if(r&&r.width!==0&&r.height!==0){var D=this.player.getPlayerSize();if(D&&D.width!==0&&D.height!==0){var Y=r.width/r.height;var V=0;for(var L=-1,T=0;T<pJa.length;T++){var I=Math.abs(D.width-pJa[T]);if(L===-1||V>=I)L=T,V=I}V=heR[L];this.L&&g.Uf(this.L.element,"outline-width",Math.max(D.width,D.height)+"px");for(D=0;D<this.endscreen.elements.length;++D)if(T=this.endscreen.elements[D].id,L=this.T[T],
I=this.D[T],L&&I){var B=I.width*Y/I.aspectRatio,m=Math.round(I.width*r.width);T=Math.round(B*r.height);var G=r.left+Math.round(I.left*r.width),M=r.top+Math.round(I.top*r.height);g.K6(L.element,m,T);g.$O(L.element,G,M);g.U3(L.element,tQe);m>256||T>256?g.yO(L.element,"ytp-ce-large-round"):m>96||T>96?g.yO(L.element,"ytp-ce-medium-round"):g.yO(L.element,"ytp-ce-small-round");g.U3(L.element,iBS);m=I.left+I.width/2;I=I.top+B/2;g.yO(L.element,m<=.5&&I<=.5?"ytp-ce-top-left-quad":m>.5&&I<=.5?"ytp-ce-top-right-quad":
m<=.5&&I>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.U3(L.element,heR);g.yO(L.element,V);(L=g.HJ(document,"div","ytp-ce-expanding-overlay-body",L.element)[0])&&g.Uf(L,"height",T+"px")}}}}};
g.x.onCueRangeEnter=function(r){if(this.endscreen)if(r.getId()==="ytp-ce-in-endscreen")vn(this,this.endscreen.impressionUrls),(r=g.Rp())&&this.endscreen.visualElement&&g.ML(r,this.endscreen.visualElement),this.W&&(g.yO(this.W,"ytp-ce-element-show"),this.W.removeAttribute("aria-hidden"),this.player.Fy()?g.yO(this.W,"ytp-ce-hide-button-lower"):g.Wf(this.W,"ytp-ce-hide-button-lower"));else{r=r.getId().substring(15);var D=this.T[r],Y=this.D[r];g.yO(D.element,"ytp-ce-element-show");D.element.removeAttribute("aria-hidden");
D=this.player.getRootNode();g.yO(D,"ytp-ce-shown");vn(this,Y.impressionUrls);(D=g.Rp())&&g.ML(D,Y.visualElement);this.player.Z().N&&this.player.KP("endscreenelementshown",r)}};
g.x.onCueRangeExit=function(r){if(r.getId()==="ytp-ce-in-endscreen")this.W&&(g.Wf(this.W,"ytp-ce-element-show"),this.W.setAttribute("aria-hidden","true"));else{r=r.getId().substring(15);var D=this.T[r];g.Wf(D.element,"ytp-ce-element-show");D.element.setAttribute("aria-hidden","true");D=this.player.getRootNode();g.Wf(D,"ytp-ce-shown");this.player.Z().N&&this.player.KP("endscreenelementhidden",r)}};
g.x.s$z=function(r){var D=this;r.target===window&&(new g.LN(function(){for(var Y=g.F(Object.values(D.T)),V=Y.next();!V.done;V=Y.next())g.U3(V.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.x.fC=function(r){for(var D=g.F(Object.values(this.T)),Y=D.next();!Y.done;Y=D.next())Y=Y.value,r?Y.element.setAttribute("hidden",""):Y.element.removeAttribute("hidden")};
g.x.T1o=function(r){this.W&&this.player.getRootNode().removeChild(this.W);r&&(g.yO(r,"ytp-ce-hide-button-container"),this.W=r,g.NI(this.player,this.W,4))};
var pJa=[346,426,470,506,570,640,853,1280,1920],heR="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),iBS=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],tQe=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var q15={SkP:"current",OG$:"new"};var gCe={CLOSE:"close",Krv:"openUrl",SUBSCRIBE:"subscribe"},$gR={X$z:"click",CLOSE:"close",icT:"hidden",nkT:"rollOut",VW$:"rollOver",Xdz:"shown"};OuT.prototype.HY=function(){var r=pr5(this,function(D){return D.type==="openUrl"&&D.url!=null});
return r?r.url:null};
var $Er={fOz:"anchored",Vz:"branding",CHANNEL:"channel",FHI:"cta",gNT:"highlightText",f$T:"label",PLAYLIST:"playlist",POPUP:"popup",YlI:"speech",SUBSCRIBE:"subscribe",x8_:"title",VIDEO:"video",QeF:"website"},gHr={Vz:"branding",n__:"card",hkz:"drawer",lgv:"highlight",zoD:"marker",gkY:"promotion",TEXT:"text",Djz:"widget"};g.U(oH,g.N);g.x=oH.prototype;g.x.addCueRange=function(r,D,Y,V,L){r=new g.Qe(r,D,{id:Y,namespace:"annotations_module"});V&&this.b$.set(r,V);L&&this.UI.set(r,L);this.context.C.a$([r],1)};
g.x.nk=function(){this.context.T.subscribe("resize",this.C9,this)};
g.x.gD=function(){return this.element};
g.x.Nk=function(r,D,Y,V,L,T){if(this.JT)return!1;T&&(T.stopPropagation(),T.preventDefault());this.navigate(r,Y,V,L);return!1};
g.x.show=function(){};
g.x.hide=function(){};
g.x.destroy=function(){g.mJ(this.gD())};
g.x.C9=function(){};
g.x.navigate=function(r,D,Y,V){var L=this,T=eq(r);if(T){var I=ECq(T,r.target),B=function(){r.W&&L.context.C.pauseVideo();var m=L.context.videoData.Jj||!1,G=g.Qk(T||"");m&&G&&(G.v||G.list)?L.context.C.Ie(G.v,D,G.list,!1):g.w1(T||"",I==="current"?"_top":void 0,D)};
I==="new"&&(B(),B=null);Il(this.context.logger,Y,B,V);llT(T)||(Y=g.Rp(),V=D.itct,Y&&V&&g.s6(Y,g.K0(V)))}};
g.x.F2=function(){this.b$.clear();this.UI.clear();g.N.prototype.F2.call(this)};
g.x.createElement=function(r){r=new g.Z(r);g.v(this,r);return r.element};g.U(zpe,oH);g.x=zpe.prototype;g.x.pc=function(){this.LP&&wW(this,this.LP)};
g.x.isAvailable=function(){var r;if(r=!!this.cards.length)(r=this.C.getRootNode())?(r=g.lc(r),r=173<r.width&&173<r.height):r=!1;return r};
g.x.C9=function(){var r=this.isAvailable();g.Ef(this.gD(),r);g.Fw(this.context.C.getRootNode(),g.fH.IV_DRAWER_ENABLED,r);Om(this.C)};
g.x.destroy=function(){this.C.e9(!1);try{this.C.getRootNode().removeChild(this.S)}catch(r){}g.aY(this.Tv);g.Nj(this.y_);this.u$&&this.u$.dispose();this.j&&this.j.dispose();oH.prototype.destroy.call(this)};
g.x.f9=function(){var r=this;this.context.W.listen(g.fB("iv-drawer-close-button",this.S),"click",this.mw,this);this.context.W.listen(this.T,"touchend",function(){r.gT.start()});
this.context.W.listen(this.T,"scroll",this.R2,this);this.context.T.subscribe("onHideControls",function(){r.eD=!0});
this.context.T.subscribe("onShowControls",function(){r.eD=!1});
this.context.T.subscribe("onVideoAreaChange",function(){r.eD=g.s3(r.C.getRootNode(),"ytp-autohide")});
this.Tv.push(g.yg("iv-button-shown",this.oKF,this));this.Tv.push(g.yg("iv-button-hidden",this.d22,this));cRa(this)};
g.x.findLastIndex=function(r){if(this.cards.length===0)return 0;var D=g.nr(this.cards,function(Y){return r.O7.startMs>Y.O7.startMs||r.O7.startMs===Y.O7.startMs&&r.O7.timestamp>=Y.O7.timestamp?!0:!1});
return D===-1?0:D+1};
g.x.mw=function(){if(this.L){Il(this.context.logger,VP(this).tf.close);var r=g.Rp();r&&this.N&&g.s6(r,this.N);f_(this)}};
g.x.R2=function(){g.Fw(this.S,"iv-drawer-scrolled",this.T.scrollTop>0)};
g.x.oKF=function(){var r=g.Rp(),D=VP(this);D=D?D.Qs:this.Qs;r&&D&&g.j$(r,[D])};
g.x.d22=function(){var r=g.Rp(),D=VP(this);D=D?D.Qs:this.Qs;r&&D&&g.QE(r,[D])};
g.x.xB=function(){var r=VP(this);Il(this.context.logger,r.tf.vO);var D=g.Rp();if(D&&r)if(this.C.V("web_infocards_teaser_show_logging_fix")){var Y=[];r.QB&&Y.push(r.QB);r.Qs&&Y.push(r.Qs);Y.length>0&&g.j$(D,Y)}else g.j$(D,[r.QB,r.Qs])};
g.x.MPI=function(){var r=g.Rp(),D=VP(this);r&&D&&g.QE(r,[D.QB])};
g.x.SA=function(r){var D=VP(this),Y=g.Rp();this.W?r?(r=this.context.logger,Il(r,D.tf.f$),r.C.sendVideoStatsEngageEvent(4,void 0),Y&&D.QB&&g.s6(Y,D.QB)):(r=this.context.logger,Il(r,D.tf.f$),r.C.sendVideoStatsEngageEvent(4,void 0),Y&&D.Qs&&g.s6(Y,D.Qs)):(r=this.context.logger,Il(r,D.tf.f$),r.C.sendVideoStatsEngageEvent(4,void 0),Y&&this.Qs&&g.s6(Y,this.Qs))};g.U(Lv,oH);Lv.prototype.nk=function(){oH.prototype.nk.call(this);Hua(this)};
Lv.prototype.show=function(){oH.prototype.show.call(this);var r=g.Rp(),D=this.annotation.data;r&&D&&(D=D.session_data)&&g.j$(r,[g.K0(D.itct)])};
Lv.prototype.hide=function(){oH.prototype.hide.call(this);var r=g.Rp(),D=this.annotation.data;r&&D&&(D=D.session_data)&&g.QE(r,[g.K0(D.itct)])};g.U(TV,Lv);
TV.prototype.show=function(){if(!this.isActive){Lv.prototype.show.call(this);if(!this.N){g.yO(this.gD(),"iv-branding");var r=this.annotation.data;this.T=this.createElement({G:"img",hT:["branding-img","iv-click-target"],J:{"aria-label":"Channel watermark",src:r.image_url,width:r.image_width,height:r.image_height}});g.Ef(this.T,!1);var D=this.createElement({G:"button",hT:["branding-img-container","ytp-button"]});D.appendChild(this.T);this.gD().appendChild(D);var Y=this.annotation.HY();Y&&Pn(this,D,
Y,this.annotation.id,r.session_data);this.context.C.V("disable_branding_context")||DEq(this,r);this.N=!0}g.Ef(this.gD(),!0);this.isActive=!0;if(this.T){try{flW(this,this.T)}catch(V){}g.yO(this.context.C.getRootNode(),"ytp-branding-shown");this.context.C.getRootNode().style.setProperty("--branding-image-width",this.T.getAttribute("width")+"px")}}};
TV.prototype.hide=function(){this.isActive&&(Lv.prototype.hide.call(this),g.Ef(this.gD(),!1),this.isActive=!1,g.Wf(this.context.C.getRootNode(),"ytp-branding-shown"))};
TV.prototype.destroy=function(){this.W&&(this.W.dispose(),this.W=null);g.Wf(this.context.C.getRootNode(),"ytp-branding-shown");Lv.prototype.destroy.call(this)};g.U(VQS,Lv);g.x=VQS.prototype;g.x.show=function(){this.isActive||(Lv.prototype.show.call(this),this.Y||(TIM(this),this.Y=!0),g.Ef(this.gD(),!0),g.Jo(function(){g.Wf(this.gD(),"iv-promo-inactive")},100,this),this.gD().removeAttribute("aria-hidden"),this.isActive=!0,mE_(this),IPc(this),xE_(this,this.D))};
g.x.hide=function(){this.isActive&&(g.yO(this.gD(),"iv-promo-inactive"),this.isActive=!1,this.gD().setAttribute("aria-hidden","true"))};
g.x.Nk=function(r,D,Y,V,L,T){return this.isCollapsed?!1:Lv.prototype.Nk.call(this,r,D,Y,V,L,T)};
g.x.yTz=function(r){this.K=!0;LIR(this,500,r)};
g.x.HPv=function(){this.K=!1;BIW(this)};
g.x.hYo=function(r){r.stopPropagation();this.hide()};
g.x.eYF=function(r){r.stopPropagation();mE_(this);this.isCollapsed=!0;g.yO(this.gD(),"iv-promo-collapsed-no-delay");this.j.start()};
g.x.destroy=function(){this.j.dispose();Lv.prototype.destroy.call(this)};g.U(MQ_,g.uF);g.x=MQ_.prototype;g.x.f3=function(r,D){if(!OBr(this.player.Z().playerStyle))return null;switch(r){case "loadCustomAnnotationsXml":return(r=g.Pv(D))&&aPe(this,r),!0;case "removeCustomAnnotationById":return D&&this.W&&(vCS(this.W,D),Om(this.player)),!0}return null};
g.x.getOptions=function(){return OBr(this.player.Z().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.x.C4=function(){var r=this.player.Z(),D=this.player.getVideoData(),Y=r.annotationsLoadPolicy||D.annotationsLoadPolicy;return g.xp(D)||this.player.isMutedByEmbedsMutedAutoplay()?!1:Y===1&&!D.mL||r.rT.get(D.videoId)||g.NO(D)||g.vA(D)?!0:!1};
g.x.HE=function(){if(this.L){var r=this.player.Rg().getVideoContentRect(!0);g.K6(this.L.element,r.width,r.height);g.$O(this.L.element,r.left,r.top)}if(this.W){var D=this.player.nG();r=this.W;D=D.width;g.Fw(r.S,"iv-drawer-small",D<=426);g.Fw(r.S,"iv-drawer-big",D>=1280)}};
g.x.ij=function(r){Q8q(this,r.state);g.X(r.state,2)&&(this.Fy()&&this.Re()&&this.player.getPresentingPlayerType()!==2&&this.DB(!1),this.e9(!1))};
g.x.load=function(){function r(I){var B=D.loadNumber;D.j=null;D.loaded&&D.loadNumber===B&&D.player.getVideoData().videoId===V&&(I=g.gX(I)&&I.responseXML?I.responseXML:null)&&(aPe(D,I),g.yO(D.player.getRootNode(),"iv-module-loaded"))}
var D=this;g.uF.prototype.load.call(this);Q8q(this,this.player.getPlayerStateObject());this.loadNumber++;var Y=this.player.getVideoData(),V=Y.videoId;g.MK()&&(r=WIr(this,r));var L={format:"XML",onFinish:r,onError:function(){D.j=null},
urlParams:{}};Y.isPharma&&(L.urlParams.pharma="1");L.method="POST";L.withCredentials=!0;var T=this.player.Z().rT.get(V);T&&UE_(L,T);T=T&&(T.LF||T.eK);if(!Y.FI||T)Y.UI?s8T(this,Y.UI,L):(this.N=function(){if(!D.K)D.onVideoDataChange(L);var I=D.player.getVideoData();(I==null?0:g.S7(I))&&!D.Tv&&kla(D,I)},this.player.addEventListener("videodatachange",this.N));
g.NI(this.player,this.L.element,4);this.HE();(T=g.NO(Y))&&qPx(this,T);(T=g.vA(Y))&&T.featuredChannel&&AUc(this,T.featuredChannel,T.annotationId||"branding",Y.videoId||null,Y.eventId||null);this.xx=g.fB("ytp-cards-button",this.player.getRootNode());g.S7(Y)&&kla(this,Y)};
g.x.onVideoDataChange=function(r){var D=this.player.getVideoData();D.UI&&s8T(this,D.UI,r)};
g.x.unload=function(){this.player.Me("annotations_module");for(var r=g.F(Object.keys(this.D)),D=r.next();!D.done;D=r.next())this.D[D.value].destroy();this.Y=null;this.W&&(this.W.destroy(),this.W=null,Om(this.player));this.K=!1;this.j&&(this.j.abort(),this.j=null);this.Tv=!1;this.D={};this.T.hide();g.uF.prototype.unload.call(this);this.L.detach();this.N&&(this.player.removeEventListener("videodatachange",this.N),this.N=null)};
g.x.H3=function(r){r===this.player.getVideoData().videoId&&(this.loaded?FI0(this):this.load())};
g.x.Fy=function(){var r;return((r=this.W)==null?void 0:r.isAvailable())||this.Tv};
g.x.Re=function(){return!!this.W&&this.W.L};
g.x.DB=function(r,D,Y){D=D===void 0?!1:D;this.Fy();this.W&&(r?Y?Hn(this.W,Y,D):Hn(this.W,"YOUTUBE_DRAWER_AUTO_OPEN",D):f_(this.W))};
g.x.e9=function(r,D){this.player.publish(r?"cardsteasershow":"cardsteaserhide",D)};
g.x.F2=function(){this.player.Z().rT.unsubscribe("vast_info_card_add",this.H3,this);g.Wf(this.player.getRootNode(),g.fH.IV_DRAWER_OPEN);for(var r=this.LP,D=g.P3,Y=0,V=r.length;Y<V;Y++)D.xI(r[Y]);this.LP.length=0;g.uF.prototype.F2.call(this)};
g.x.createElement=function(r){r=new g.Z(r);g.v(this,r);return r.element};g.Fx("annotations_module",MQ_);g.Fx("creatorendscreen",IlW);})(_yt_player);
